import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import Nav from "@/app/ui/Nav";
import "./globals.css";

const commissioner = Commissioner({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crowfunding product page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={commissioner.className}>
        <header className="fixed top-0 z-50 w-full bg-gradient-to-b from-black/60 px-6">
          <Nav />
        </header>
        {children}
      </body>
    </html>
  );
}
